### ISSUE TITLE
Optimal checkpointing of reverse differentiation has been already solved

### ISSUE THREAD

**Issue by bdauvergne** [openai/gradient-checkpointing#1]
http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.455.4143&rep=rep1&type=pdf

**Comment by andersk** [comment]
Optimal strategy for a chain of n > 1 steps using at most m simultaneous checkpoints:

1. Binary search for the integer 0 < n′ < n such that the [generalized binomial coefficient](https://en.wikipedia.org/wiki/Binomial_coefficient#Binomial_coefficients_as_polynomials) (mn/n′; m) is as close as possible to n.
2. Perform the first n − n′ forward steps and place a checkpoint.
3. Recursively use the optimal strategy for the last n′ steps using at most m − 1 simultaneous checkpoints.
4. Recursively use the optimal strategy for the first n − n′ steps using at most m simultaneous checkpoints.

I’m not sure if this is exactly what the above paper proposes, but I’ve tested this against the dynamic programming optimum and it seems to match perfectly.
