### ISSUE TITLE
Wrong timeline computation

### ISSUE THREAD

**Issue by gchlebus** [openai/gradient-checkpointing#10]
`peak_memory` for my model running completely on a cpu returns always 0. Could it be that in the snippet below the last line should read `line = [node.all_start_micros, node.node_name, output_bytes, "unknown"]`? 
https://github.com/openai/gradient-checkpointing/blob/b2b7def2e15f2607c14c5b32fb8fa4f892489484/test/mem_util.py#L100-L106

**Comment by yaroslavvb** [comment]
I think what's happening is that you are using an older version of TensorFlow and line "node.output[0].tensor_description.allocation_description.requested_bytes" throws an exception.

Do the tests pass? They pass on my laptop which has no GPU available

**Comment by gchlebus** [comment]
You were right, installing `tf-nightly` fixed the problem. The `mem_util_test.py`passes. What is the reason for retrieving the `output_bytes` out of the `allocation_description`, when it is not used in the code at all?

**Comment by gchlebus** [comment]
Thanks for the clarification. I guess, this issue can be closed.
