### ISSUE TITLE
memory_test.py failed

### ISSUE THREAD

**Issue by majia-yu** [openai/gradient-checkpointing#16]
Hey guys,

Your work is great! 

I tried to run the tests but failed. The error message is (I modified the code to print peak_memory):

Traceback (most recent call last):
  File "memory_test.py", line 677, in <module>
    test_chain()
  File "memory_test.py", line 119, in test_chain
    assert peak_memory > 2e6, peak_memory
AssertionError: 0

Please help me if you can. :)

**Comment by yaroslavvb** [comment]
You need Tensorflow version 1.5

**Comment by majia-yu** [comment]
okay, thanks!
