### ISSUE TITLE
TF 1.6rc1 Support

### ISSUE THREAD

**Issue by michaelklachko** [openai/gradient-checkpointing#17]
Is it included in 1.6rc1, or do we still need to install nightly?

**Comment by yaroslavvb** [comment]
1.5.0 or later should work

**Comment by michaelklachko** [comment]
I just installed 1.6rc1 on Ubuntu, and I don't see it:

>>> print tf.__version__
1.6.0-rc1
>>>
>>> import memory_saving_gradients
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named memory_saving_gradients

**Comment by yaroslavvb** [comment]
You have to clone the repo/install it separately, it's not part of official TF (nor ever will be)
