### ISSUE TITLE
Extremely slow when running on distributed tensorflow with horovod

### ISSUE THREAD

**Issue by ChenChuang** [openai/gradient-checkpointing#33]
We are working to use gradient-checkpointing on distributed tensorflow(horovod: https://github.com/uber/horovod)

configuration as follows:
model: resnet50
input: synthetic data with 1k class number
horovod: horovod-0.12.1-py3.6-linux-x86_64 with NCCL2
tensorflow: 1.8.0
gradient-checkpointing: memory
experiment:
1) 1GPU on P40
2) 8GPU on P40, each GPU occupied by one MPI process.

The result on single GPU looks promising, with memory usage dropping from 7820.39MB to 3580.35MB while training speed drops from 152.51examples/sec to 115.68examples/sec. But the result on multiple(8) GPUs is not good. Memory usage drops from 7914.49MB to 3811.62MB, which is as expected.
But training speed drops from 143.63examples/sec per GPU to 6.71examples/sec. 

Anyone could give us a hint on solving this issue?

**Comment by yaroslavvb** [comment]
Hm, not sure what Horovod is doing here...are things still running on GPU?

**Comment by ChenChuang** [comment]
We have solved the problem. The reason is that device field of original op is discarded in when `ge.copy_with_input_replacements`, which results in all copied ops being assigned to `/job:worker/task:0/gpu:0`, instead of their original tower. The fix is explicitly copying device field after ops are copied.
