### ISSUE TITLE
Publish this on Pypi

### ISSUE THREAD

**Issue by LucaCappelletti94** [openai/gradient-checkpointing#56]
Hello,

First of all, thank you for making this work public!

I have noticed that this package is not available on Pypi, and this makes distributing this package harder than it needs to be.

Would you be interested in doing so? [I have published a few packages on there](https://pypi.org/user/LucaCappelletti94/) so if you need a hand doing so I'd be happy to help out. It should be a matter of a few minutes from start to finish.

Thank you and have a nice day,
Luca

**Comment by yaroslavvb** [comment]
well, does anyone still use this package? It doesn't work on TF 2.0, needs TF 1.xxx

**Comment by LucaCappelletti94** [comment]
Hello @yaroslavvb, sadly I suppose you are right, I was just overjoyed to find an implementation of this and I went to install it, found it was not yet on Pypi and sort of skipped a few steps. 
I noticed almost immediately afterwards it uses the graph editor (RIP), so it will not work on the 2.x - do you think there is any chance to update it? I gave a try with [this graph editor alternative](https://github.com/CODAIT/graph_def_editor) but I think any result achieved with that may be quite more difficult to use than the method injection that was possible with your package.
