### ISSUE TITLE
How does gradient checkpointing relate to reversible layers?

### ISSUE THREAD

**Issue by styleex** [openai/gradient-checkpointing#57]
While studying ways to optimize GPU memory consumption, I found two approaches:
1. Gradient checkpointing
2. Reversible layer (from reformer paper)

Can you explain if there is a connection between them and which of the methods is more relevant now?

**Comment by yaroslavvb** [comment]
Reversible layers don't need to store activations so you don't need
checkpointing. However there does not appear to be competitive architecture
which uses reversible layers

**Comment by styleex** [comment]
@yaroslavvb Understood, thanks for the answer!
